--APRETAR F5 MUCHAS VECES PARA DROPEAR TODAS LAS TABLAS--
DROP TABLE [dbo].[UserType]
DROP TABLE [dbo].[Order]
DROP TABLE [dbo].[Item]
DROP TABLE [dbo].[ItemHistory]
DROP TABLE [dbo].[Gender]
DROP TABLE [dbo].[Customer]
DROP TABLE [dbo].[Category]
DROP TABLE [dbo].[Product]
DROP TABLE  [dbo].[CategoryDupli]
DROP TABLE [dbo].[CategorySinDupli]
DROP FUNCTION [dbo].[Path_Category_Item]
DROP PROCEDURE [dbo].[ItemToITemHistoryDay]
DROP TABLE [dbo].[CategorySinDupli]